language: java
sudo: false

jdk:
  - oraclejdk8

branches:
  only:
    - master

env:
  - TERM=dumb

before_install:
 - chmod +x gradlew

install:
 -

script:
  - echo "TO-DO";

notifications:
  email: false