language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

sudo: false
env:
  - TERM=dumb

cache:
  directories:
  - $HOME/.gradle

before_install:
 - chmod +x gradlew

install:
 - gradle assemble

script:
  - git add .

notifications:
  email: false